name: Makefile CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
  working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pwd
      run: pwd
    - name: Run tests
      run: make

